### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by raspi** [sahib/rmlint#9]
I'm trying to compile with Ubuntu 11.10 64 bit
# make -j 4

src/md5.o: In function `md5_file_mmap':
md5.c:(.text+0xe39): undefined reference to`sqrt'
src/md5.o: In function `md5_file_fread':
md5.c:(.text+0x1007): undefined reference to`sqrt'
src/filter.o: In function `sheduler_jointhreads':
filter.c:(.text+0xf8): undefined reference to`pthread_join'
src/filter.o: In function `sheduler_cb':
filter.c:(.text+0x238): undefined reference to`sqrt'
filter.c:(.text+0x421): undefined reference to `pthread_create'
filter.c:(.text+0x441): undefined reference to`pthread_join'
src/filter.o: In function `start_processing':
filter.c:(.text+0x12bd): undefined reference to`pthread_create'
collect2: ld returned 1 exit status
make: **\* [rmlint] Error 1
