### ISSUE TITLE
Compiling error on lib/cmdline.c on OS X 10.9

### ISSUE THREAD

**Issue by simmac** [sahib/rmlint#177]
Apparently rmlint doesn't compile on OS X 10.9, at least that's what the brew-bot says (I don't have a Mavericks machine right now, but it works fine with 10.10 and 10.11):
```
Compiling ==> lib/cmdline.c
[1mlib/cmdline.c:394:18: [0m[0;1;31merror: [0m[1muse of undeclared identifier 'AT_FDCWD'[0m
    if(faccessat(AT_FDCWD, path, R_OK, AT_EACCESS) != 0) {
[0;1;32m                 ^
[0m1 error generated.
scons: *** [lib/cmdline.o] Error 1
```

As I don't really have a complete overview over the rmlint-code, could someone help me figuring out if there is any missing dependency or something?

**Comment by sahib** [comment]
That's indeed because [10.9 does not seem to define AT_FDCWD](https://github.com/NixOS/nix/issues/465). 
I tried to work around that issue in 0be19276f8c5308df287f5298e6f63ca21e29a78. Please try again with that if possible.

**Comment by simmac** [comment]
Thank you! I would be happy if anyone running 10.9 could test it, otherwise I would need some more time (getting my hands on a 10.9 (v)machine.

**Comment by simmac** [comment]
@sahib This is what I get now:

```
lib/cmdline.c:405:8: warning: implicit declaration of function 'faccessat' is invalid in C99 [-Wimplicit-function-declaration]
    if(faccessat(session->current_dir_fd, path, R_OK, AT_EACCESS) != 0) {
       ^
lib/cmdline.c:405:55: error: use of undeclared identifier 'AT_EACCESS'
    if(faccessat(session->current_dir_fd, path, R_OK, AT_EACCESS) != 0) {
                                                      ^
1 warning and 1 error generated.
scons: *** [lib/cmdline.o] Error 1
scons: building terminated because of errors.
```

Detailed build log: https://travis-ci.org/simmac/rmlint/jobs/120027599

**Comment by sahib** [comment]
Thank you for the log. Seems 10.9 is lacking more than I thought.
I tried to push another fix at the develop branch which should fallback to the normal ``access()`` function.

**Comment by simmac** [comment]
Great, it does build now, thanks!
Please let me know when you create a new tag so I can submit the homebrew formula.

If you are interested in the travis-log: https://travis-ci.org/simmac/rmlint/jobs/120075159

**Comment by sahib** [comment]
I will wait a bit if other issues arise. Otherwise my packagers might give me a sinister eye.
Does your homebrew formula already install the manpage?

**Comment by simmac** [comment]
Okay, no problem.

What do I need for the manpage installation? I thought I included all dependencies needed?

**Comment by sahib** [comment]
You need sphinx, the documentation generator. :smile:
From your build log:

    ==> Downloading https://homebrew.bintray.com/bottles/sphinx-2.2.10.mavericks.bot
    ==> Pouring sphinx-2.2.10.mavericks.bottle.tar.gz
    ==> Caveats
    This is *not* sphinx - the Python Documentation Generator.
    To install sphinx-python use pip.
    [...]


Well, that's not the one. That's [the search server named Sphinx](http://sphinxsearch.com/).
This results in this output far down:

    Building manpage from rst...
    Unable to find sphinx binary in PATH
    Will be unable to build manpage or html docs
    gzip_file(["docs/rmlint.1.gz"], ["docs/_build/man/rmlint.1"])
    gzip: can't stat: /Users/travis/build/simmac/rmlint/docs/_build/man/rmlint.1 (/Users/travis/build/simmac/rmlint/docs/_build/man/rmlint.1): No such file or directory
    Warning: could not gzip /Users/travis/build/simmac/rmlint/docs/_build/man/rmlint.1 to /Users/travis/build/simmac/rmlint/docs/rmlint.1.gz: Command 'gzip -c /Users/travis/build/simmac/rmlint/docs/_build/man/rmlint.1 > /Users/travis/build/simmac/rmlint/docs/rmlint.1.gz' returned non-zero exit status 1

**Comment by sahib** [comment]
Also, you might want to add ``json-glib`` to the dependency list:

    $ brew install json-glib

This enables ``--replay`` and a few other niceties.

**Comment by simmac** [comment]
Haha, okay, thanks! :D
I just went through the dependencies list on the homepage, checking which packages are in brew.

**Comment by sahib** [comment]
@simmac: Released 2.4.4 with the mentioned build fixes
