### ISSUE TITLE
Refuses to compile on Mac OS X 10.6

### ISSUE THREAD

**Issue by ghost** [sahib/rmlint#6]
The `./configure` step works just fine without issue, but when it comes to running `make`, I get the following error:

```
-> Compiling src/md5.c
src/md5.c:1: error: bad value (native) for -march= switch
src/md5.c:1: error: bad value (native) for -mtune= switch
make: *** [src/md5.o] Error 1
```
